 //Program illustrates how data in the variables are manipulated.
 #include <iostream> 
#include <string>
 using namespace std;
 int main()
{
    int n1, n2;
    double sale;
    char first;
    string str;
    n1 = 4;
    cout <<"Number1 = "<<n1<<endl;
    n2 = 4*5 -11;
    cout <<"Number2 = "<<n2<<endl;
    sale = 0.02 * 1000;
    cout <<"Sale = "<<sale<<endl;
    first = 'D';
    cout <<"First = "<<first<<endl;
    str = "It is a sunny day.";
    cout <<"str = "<<str;
    return 0;
 }