// This program illustrates how output statements work.
 #include <iostream>
 using namespace std;
 int main()
 {
    int a, b;
    a = 65;
    b = 78;
    cout << 29 / 4<<endl;
    cout << 3.0 / 2<<endl;
    cout <<"Hello there.\n"; 
    cout <<7<<endl; 
    cout <<3 + 5<<endl; 
    cout <<"3 + 5"; 
    cout <<" **"; 
    cout <<endl; 
    cout <<2 +3 * 6<<endl; 
    cout <<"a"<<endl; 
    cout <<a<<endl; 
    cout <<b<<endl;  
    return 0;
 }