#include <iostream>
#include <string>
using namespace std;
int main()
{
    int num;
    double height;
    string name;
    cout<< "Enter an integer: ";
    cin >> num;
    cout << endl;
    cout << "num: "<<num<<endl;
    cout << "Enter the first name: ";
    cin >> name;
    cout << "Enter the height: ";
    cin >> height;
    cout <<"Name: "<<name<<endl;
    cout<<"Height: "<<height;
    return 0;
}
